### ISSUE TITLE
Support optional elements in structs

### ISSUE THREAD

**Issue by kbirken** [COVESA/capicxx-core-tools#16]
In AUTOSAR 18.10, optional struct fields have been introduced. In order to achieve compatibility of CommonAPI SOME/IP and AUTOSAR on the IPC level, it would be necessary to support optional struct fields also for CommonAPI SOME/IP. 

As Franca IDL doesn't support optional struct fields, this would have to be defined on the deployment level, e.g. by the following specification:

```
for struct_fields {
  IsOptional : boolean (default: false);
} 
```

The optional-flag is often combined with the possibility of setting a default value for the specific field. This is currently difficult to accomplish in Franca deployment models.

Note: It is not quite clear yet how the C++ API for this would look like.

**Comment by BrunoLSilvaCTW** [comment]
Hi @kbirken, support for optional elements in structs is not planned for CommonAPI.

**Comment by kbirken** [comment]
Hi @BrunoLSilvaCTW, thanks for this response from the past. :-)
