### ISSUE TITLE
Compile error on HelloWorld

### ISSUE THREAD

**Issue by sbenyamin** [COVESA/capicxx-core-tools#21]
Hi I have downloaded the following tools, all version 3.1.12.2
commonapi-generator.zip (3.1.12.2 from https://github.com/GENIVI/capicxx-core-tools/releases)
commonapi-dbus-generator.zip (3.1.12.2 from https://github.com/GENIVI/capicxx-dbus-tools/releases)
commonapi-someip-generator.zip (3.1.12.2 from https://github.com/GENIVI/capicxx-someip-tools/releases)
capicxx-core-runtime-3.1.12.2.tar.gz
capicxx-dbus-runtime-3.1.12.2.tar.gz
capicxx-someip-runtime-3.1.12.2.tar.gz

They do not all seem to be the latest, but I wanted to use the exact same revision as I saw this recommendation in one of the README files.  Can someone tell me if this combination should work. I am getting error messages that indicate that the calls from E01HelloWorld in the capicxx-core-tools version 3.1.12.2 is not compatible with the libraries generated by capicxx-dbus-runtime. See bold error message below.

/usr/include/c++/7/bits/shared_ptr.h:706:39:   required from ‘std::shared_ptr<_Tp> std::make_shared(_Args&& ...) [with _Tp = v0::commonapi::examples::E01HelloWorldDBusStubAdapter<v0::commonapi::examples::E01HelloWorldStub>; _Args = {const CommonAPI::DBus::DBusAddress&, const std::shared_ptr<CommonAPI::DBus::DBusProxyConnection>&, std::shared_ptr<v0::commonapi::examples::E01HelloWorldStub>}]’
/home/lab1/SOME-IP/capicxx-core-tools/CommonAPI-Examples/E01HelloWorld/src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusStubAdapter.cpp:21:207:   required from here
/home/lab1/SOME-IP/capicxx-core-tools/CommonAPI-Examples/E01HelloWorld/src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusStubAdapter.hpp:103:7: **error: no matching function for call to** ‘CommonAPI::DBus::DBusGetAttributeStubDispatcher<v0::commonapi::examples::E01HelloWorldStub, CommonAPI::Version>::DBusGetAttributeStubDispatcher(void (v0::commonapi::examples::E01HelloWorldStub::*)(bool), const CommonAPI::Version& (v0::commonapi::examples::E01HelloWorldStub::*)(std::shared_ptr<CommonAPI::ClientId>), const char [3])’
     > E01HelloWorldDBusStubAdapterInternal<_Stub, _Stubs...>::getE01HelloWorldInterfaceVersionStubDispatcher(&E01HelloWorldStub::lockInterfaceVersionAttribute, &E01HelloWorldStub::getInterfaceVersion, "uu");
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Thank you
-saied

**Comment by goncaloalmeida** [comment]
This problem is still occurring?

**Comment by sbenyamin** [comment]
Thank you for responding.  This was 4 years ago, we no longer need help.
