### ISSUE TITLE
Build errors [Ubuntu 18.04| maven 3.6.0

### ISSUE THREAD

**Issue by 007herelsp** [COVESA/capicxx-core-tools#27]
hi sir:

when i try to compile the capicxx-core-tools, as described in the README.md file. 
I have a compilation error as shown in the bash reported below:
skip compiling sources because the configured directory '[/home/test/capicxx-core-tools-3.2.0.1/org.genivi.commonapi.releng/src/main/java]' does not exist.

have any idea why this error occurs ?

Thank you : 

Maven Info:
Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 1.8.0_275, vendor: Private Build, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "5.4.73-1-pve", arch: "amd64", family: "unix"

**Comment by slorenz75** [comment]
Same Issue with following configuration:
Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 11.0.11, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: it_IT, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-147-generic", arch: "amd64", family: "unix"

Any idea?

**Comment by Gustavo1515** [comment]
Can you check if this issue was fixed on the last version?

Cc: @goncaloalmeida
