### ISSUE TITLE
Build errors with maven 3.6.0 on Ubuntu 18.04 

### ISSUE THREAD

**Issue by PlutusCN** [COVESA/capicxx-core-tools#28]
Hi everyone:

when I try to compile the capicxx-core-tools, as described in the README.md file.
**Richard@Ubuntu18.04:~/3rdparty/capicxx-core-tools-3.2.0.1/org.genivi.commonapi.core.releng$ mvn -Dtarget.id=org.genivi.commonapi.core.target clean verify** 

I have some compilation warnings & errors as shown in the bash reported below: 
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[WARNING] Failed to access p2 repository http://download.eclipse.org/eclipse/updates/4.9, use local cache. Unable to read repository at http://download.eclipse.org/eclipse/updates/4.9/compositeContent.xml.
[WARNING] Failed to access p2 repository http://download.eclipse.org/eclipse/updates/4.9/categories, use local cache. Unable to read repository at http://download.eclipse.org/eclipse/updates/4.9/categories/content.xml.
[WARNING] Failed to access p2 repository http://download.eclipse.org/eclipse/updates/4.9/R-4.9-201809060745, use local cache. Unable to read repository at http://download.eclipse.org/eclipse/updates/4.9/R-4.9-201809060745/content.xml.
[WARNING] Failed to access p2 repository http://download.eclipse.org/releases/2018-09, use local cache. Unable to read repository at http://download.eclipse.org/releases/2018-09/compositeContent.xml.
[WARNING] Failed to access p2 repository https://download.eclipse.org/technology/epp/packages/2018-09, use local cache. Unable to read repository at https://download.eclipse.org/technology/epp/packages/
... ... 
[WARNING] Failed to access p2 repository http://download.eclipse.org/tools/orbit/downloads/drops2/R20170919201930/repository, use local cache. Unable to read repository at http://download.eclipse.org/tools/orbit/downloads/drops2/R20170919201930/repository/content.xml.
[ERROR] Failed to resolve target definition /home/SMCV/pnhqv/MAXUS/3rdparty/capicxx-core-tools-3.2.0.1/org.genivi.commonapi.core.target/org.genivi.commonapi.core.target.target: Failed to load p2 metadata repository from location http://franca.github.io/franca/update_site/releases: Unable to read repository at http://franca.github.io/franca/update_site/releases/content.xml. Connection reset -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException

have any idea why these warnings & errors occur ?

Thank you !!! 

Maven Info:
Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 11.0.10, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: zh_CN, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-42-generic", arch: "amd64", family: "unix"

**Comment by dzvoid** [comment]
我也遇到了同样的问题。请问你解决了吗？

**Comment by lutzbichler** [comment]
jdk11 is not supported. Please use jdk8.

**Comment by zhhhhhhhh** [comment]
> 

请问换成1.8解决了吗
