### ISSUE TITLE
make docx failure

### ISSUE THREAD

**Issue by uniconn-corp** [COVESA/capicxx-core-tools#36]
Got failure when generate documents from docx folder. 

$ make 
mkdir -p ../doc
cp -rf images ../doc/images
cp index.html ../doc
mkdir -p ../doc/html
asciidoc \
	-a revdate=24.\ Thg 3\ 2022 \
	-a icons \
	-a iconsdir=../images/icons \
	-a imagedir=../images \
	-a version= \
	-a cppstr=cpp \
	-a tabsize=4 \
	-o ../doc/html/CommonAPICppSpecification.html \
	CommonAPICppSpecification
asciidoc: Too many arguments

Man page:     asciidoc --help manpage
Syntax:       asciidoc --help syntax
Makefile:16: recipe for target 'spec_html' failed
make: *** [spec_html] Error 1

**Comment by goncaloalmeida** [comment]
This problem is still occurring?
