### ISSUE TITLE
constants in .fidl files should be `static const` or, better, `static constexpr`

### ISSUE THREAD

**Issue by livingsilver94** [COVESA/capicxx-core-tools#37]
When constants are defined in the Franca language, I see no reason not to translate them into `static const` or `static constexpr` variables. A constant is a constant on its own, it doesn't need to depend on a struct instance to be able to access it.

For example, [this test](https://github.com/COVESA/capicxx-core-tools/blob/3.2.0.1/org.genivi.commonapi.core.verification/src/DTConstants.cpp#L118) requires an instance.

**Comment by goncaloalmeida** [comment]
This problem is still occurring?

**Comment by livingsilver94** [comment]
I don't know, I haven't used Franca for a while.
