### ISSUE TITLE
Linking Dependency Build Error 

### ISSUE THREAD

**Issue by aravinds2018** [COVESA/capicxx-core-tools#53]
With CommonAPI library iam able to generate FIDL code and build binary in ubuntu 14, but in ubuntu 22 i could generate code but couldn't build . What should be the possible reasons?
![image](https://github.com/COVESA/capicxx-core-tools/assets/104155195/bdfe6b1b-0b80-4b84-92c6-0b098a31b159)

**Comment by goncaloalmeida** [comment]
@aravinds2018 could you please test with the last release?
Thanks
