### ISSUE TITLE
does the generator support aarch64 linux?

### ISSUE THREAD

**Issue by liurunjieDW** [COVESA/capicxx-core-tools#54]
i've compiled the commonapi-core-generator in ubuntu aarch64, but the archive is still x86 and x86_64 in org.genivi.commonapi.core.cli.product/target/products/commonapi_core_generator.zip

**Comment by zhaoxin39913** [comment]
Yes, the same to me, and it's not able to execute:

**Comment by Gustavo1515** [comment]
At the current state the generator doesn't support aarch64, but you can try change it here to check if it solves the problem -> https://github.com/COVESA/capicxx-core-tools/blob/master/org.genivi.commonapi.releng/pom.xml#L73

**Comment by peigao-tw** [comment]
Yes, the same to me, and it's not able to execute. I have tried to add aarch64 config but it can not work,
[INFO] Adding repository http://download.eclipse.org/tools/orbit/downloads/drops/R20170919201930/repository
diff --git a/org.genivi.commonapi.releng/pom.xml b/org.genivi.commonapi.releng/pom.xml
index 751d120..6f0e71e 100644
--- a/org.genivi.commonapi.releng/pom.xml
+++ b/org.genivi.commonapi.releng/pom.xml
@@ -72,6 +72,11 @@
                             <ws>gtk</ws>
                             <arch>x86_64</arch>
                         </environment>
+                        <environment>
+                            <os>linux</os>
+                            <ws>gtk</ws>
+                            <arch>aarch64</arch>
+                        </environment>
                         <environment>
                             <os>macosx</os>
                             <ws>cocoa</ws>
(END)
