### ISSUE TITLE
How to configure Eclipse IDE?

### ISSUE THREAD

**Issue by dprogm** [COVESA/capicxx-core-tools#56]
Would be glad if someone can provide the steps, how to configure e.g. an Eclipse IDE to get Code Completion and other IDE features working. Currently it doesn't resolve the imports correctly. Manual editing of the `.classpath` and pointing to maven repositories helps, but is not a reliable solution. 

Is there anything I should be aware of?

**Comment by goncaloalmeida** [comment]
@dprogm please open a discussion regarding this topic :)
This section is for issues on the project.
