### ISSUE TITLE
log4j:WARN No appenders could be found for logger (org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser).

### ISSUE THREAD

**Issue by hzhang37** [COVESA/capicxx-core-tools#57]
Build common API code generate command:
mvn -Dtarget.id=org.genivi.commonapi.core.target clean verify

CommonAPI Version 3.2.0.v202309050157

issue: why there have log4j WARN log.
log4j:WARN No appenders could be found for logger (org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser).

Generate code log:
~/workspace/P2/vsomeip/CommonAPI/capicxx-core-tools/CommonAPI-Examples/E01HelloWorld$ /home/she1/workspace/P2/vsomeip/CommonAPI/capicxx-core-tools/org.genivi.commonapi.core.cli.product/target/products/commonapi_core_generator/commonapi-core-generator-linux-x86_64 --skel --dest-common ./src-gen/core/common --dest-proxy ./src-gen/core/proxy --dest-stub ./src-gen/core/stub --dest-skel ./src-gen/core/skel ./fidl/E01HelloWorld.fidl
Executing CommonAPI Core Code Generation...
Skeleton code will be created
Skeleton postfix: Default
Common output directory: ./src-gen/core/common
Proxy output directory: ./src-gen/core/proxy
Stub output directory: ./src-gen/core/stub
Skeleton output directory: ./src-gen/core/skel
Using Franca Version 0.13.1.201807231814
and CommonAPI Version 3.2.0.v202309050157
```
log4j:WARN No appenders could be found for logger (org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```
Generating code for /home/she1/workspace/P2/vsomeip/CommonAPI/capicxx-core-tools/CommonAPI-Examples/E01HelloWorld/./fidl/E01HelloWorld.fidl

**Comment by goncaloalmeida** [comment]
@hzhang37 could you please test with the last release?
Thanks
