### ISSUE TITLE
Generator binary files are missing in release capicxx-core-tools 3.2.14

### ISSUE THREAD

**Issue by wennmbj** [COVESA/capicxx-core-tools#60]
In the past the compiled generator binaries were published. I would appreciate to get the compiled binary in the release section.

Many thanks!

**Comment by goncaloalmeida** [comment]
@wennmbj please don't use the "Issues" section for this.
Please use Discussions tab.
cc @dibpinto @Gustavo1515

**Comment by wennmbj** [comment]
@Gustavo1515: I would love to use the discussion tab, but it is disabled in this repo.
