### ISSUE TITLE
The latest i.e 3.2.0.1 and 3.2.14 core tools is not generating the "StubDefault.cpp". Creating only "StubDefault.hpp" file

### ISSUE THREAD

**Issue by Siddharthav1** [COVESA/capicxx-core-tools#66]
@goncaloalmeida I checked the latest 3.2.14 release as well but still .cpp is not generated. Below are the files generated

1. TGHMStatus.hpp
2. TGHMStatusProxyBase.hpp
3. TGHMStatusProxy.hpp
4. TGHMStatusStubDefault.hpp
5. TGHMStatusStub.hpp
6. TGHMTypes.hpp

I wasn't able to reopen the oldeer issue so am linking it here : https://github.com/COVESA/capicxx-core-tools/issues/58

[Issue:58](https://github.com/COVESA/capicxx-core-tools/issues/58)

**Comment by goncaloalmeida** [comment]
@Siddharthav1 after checking internally we verified that this is the new behavior.
The StubDefault.cpp is not generated and it is not needed.
The inclusion of the .hpp should be sufficient
This was introduced with 3.2.*
